[package]
name = "rusty_tutorial"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.1"
rusty_engine = "6.0.0"

[profile.dev]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 16
